services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    ports:
      - "5432:5432"
  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev
    ports:
      - "5672:5672"
      - "15672:15672"