spring:
  application:
    name: backend
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: create-drop

backend:
  service: ${SERVICE_NAME}

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database: postgresql
  datasource:
    username: dev
    password: dev
    url: jdbc:postgresql://localhost:5432/
  data:
    redis:
      host: localhost
  rabbitmq:
    username: dev
    password: dev

backend:
  auth:
    sign: DEVKEY-dgjijasbhdgjhbasdjhufgasdogjaiuebguwebjubsjdhbfuiweagfiuwhjgbadjksbfjhawerhiohwaeiugvh aeiuz
---
spring:
  config:
    import: "optional:file:config.yml"
    activate:
      on-profile: prod
  jpa:
    database: postgresql
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
  rabbitmq:
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    host: ${RABBIT_MQ_HOST}
backend:
  auth:
    sign: ${BACKEND_SIGN_KEY}

