name: Publish
on:
  push:
    tags:
      - v**
  workflow_dispatch:
permissions:
  contents: write
jobs:
  publish:
    name: Publish Entities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21
          cache: gradle
      - name: Make executable
        run: |
          chmod +x ./gradlew
      - name: Build
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew test bootJar version
      - name: Get version
        id: version
        run: |
          echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          version=${{ steps.version.outputs.version }}
          gh release create --draft "v$version" --generate-notes
      - name: Upload artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          version=${{ steps.version.outputs.version }}
          gh release upload "v$version" "build/libs/backend-$version.jar"